### ISSUE TITLE
very good tool , it's better to print some progress info

### ISSUE THREAD

**Issue by iorilu** [dmgbuild/dmgbuild#66]
Very good tool, I used it to build my software 

it's better to print some log or progress info during processing

thanks for the work.

**Comment by freakboy3742** [comment]
Thanks for the suggestion, however:

1. dmgbuild is designed to be used as an API, in addition to being used as a command line tool itself. As such, it's not the responsibility for dmgbuild to provide progress feedback - it's the responsibility of the app *invoking* dmgbuild to provide that feedback.
2. Even if we *did* want to provide progress feedback for command-line invocation, we're extremely limited in the feedback we can provide. `dmgbuild` is, for the most part, a wrapper around command line tools - and those tools don't provide any mechanism for us to determine progress. The best we'd be able to do is an "in progress" spinner... and that doesn't really tell you anything beyond "the process hasn't returned yet" - which you can determine without having a spinner, because... the process hasn't returned yet. So we'd be adding a bunch of complexity for no major improvement in user experience.
